version: "3.7"

services:
  vscode:
    image: qmcgaw/godevcontainer
    # image: qmcgaw/godevcontainer:alpine
    # image: qmcgaw/godevcontainer:debian
    volumes:
      - ../:/workspace
      - ~/.ssh:/home/vscode/.ssh
      - ~/.ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    entrypoint: zsh -c "while sleep 1000; do :; done"
